setting:
  name: "test_mulran"
  output_root: "./experiments"
  pc_path: "./data/MulRan/kaist01"
  deskew: True
process:
  min_range_m: 3.0
  max_range_m: 80.0
sampler:
  surface_sample_range_m: 0.3
  surface_sample_n: 4
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  voxel_size_m: 0.4
  search_alpha: 0.8
loss:
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 3000
  pool_capacity: 1e7
tracker:
  source_vox_down_m: 0.6
  iter_n: 100
  eigenvalue_check: False
  GM_dist: 0.2
  valid_nn_k: 5
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.25
optimizer: # mapper
  iters: 15 # iterations per frame
  batch_size: 16384
eval:
  o3d_vis_on: False # visualize the mapping or not
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 18